# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: /usr/bin/docker build --pull -f /home/vsts/work/1/s/Web/Dockerfile -t 8cld202:web /home/vsts/work/1/s/Web
      - script: /usr/bin/docker push micmunger/8cld202:web