trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
# - stage: Build
#   displayName: Build and Push to Docker Hub
#   jobs:
#   - job: Build_Web
#     displayName: Build and Push Web
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#       - script: /usr/bin/docker build --pull -t micmunger/8cld202:web -f ./SWARM/web/Dockerfile ./
#         displayName: Build
#       - script: /usr/bin/docker login -u $(username) -p $(password) docker.io && /usr/bin/docker push micmunger/8cld202:web
#         displayName: Push  
  
#   - job: Build_MySQL_API
#     displayName: Build and Push MySQL_API
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#       - script: /usr/bin/docker build --pull -t micmunger/8cld202:mysql_api -f ./SWARM/mysql_api/Dockerfile ./
#         displayName: Build
#       - script: /usr/bin/docker login -u $(username) -p $(password) docker.io && /usr/bin/docker push micmunger/8cld202:mysql_api
#         displayName: Push

#   - job: Build_IoT_API
#     displayName: Build and Push IoT_API
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#       - script: /usr/bin/docker build --pull -t micmunger/8cld202:iot_api -f ./SWARM/iot_api/Dockerfile ./ && /usr/bin/docker login -u $(username) -p $(password) docker.io && /usr/bin/docker push micmunger/8cld202:iot_api
#         displayName: Build
#       - script: /usr/bin/docker build --pull -t micmunger/8cld202:iot_api -f ./SWARM/iot_api/Dockerfile ./ && /usr/bin/docker login -u $(username) -p $(password) docker.io && /usr/bin/docker push micmunger/8cld202:iot_api
#         displayName: Push
  
#   - job: Build_MySQL_DB
#     displayName: Build and Push MySQL_DB
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#       - script: /usr/bin/docker build --pull -t micmunger/8cld202:mysql_db ./MySQL_DB 
#         displayName: Build
#       - script: /usr/bin/docker login -u $(username) -p $(password) docker.io && /usr/bin/docker push micmunger/8cld202:mysql_db
#         displayName: Push
  
#   - job: Build_IoT_DB
#     displayName: Build and Push IoT_DB
#     pool:
#       vmImage: ubuntu-latest
#     steps:  
#       - script: /usr/bin/docker build --pull -t micmunger/8cld202:iot_db ./IoT_DB 
#         displayName: Build
#       - script: /usr/bin/docker login -u $(username) -p $(password) docker.io && /usr/bin/docker push micmunger/8cld202:iot_db
#         displayName: Push

# - stage: Start
#   displayName: Start Azure VMs
#   jobs:
#   - job: Start_Master
#     displayName: Start Master-MySQL
#     pool:
#       vmImage: ubuntu-latest
#     steps:      
#     - task: AzurePowerShell@5
#       inputs:
#         azureSubscription: 'Azure subscription 1(1aab54f1-babe-4322-95b4-185df45b9d75)'
#         ScriptType: 'InlineScript'
#         Inline: 'Start-AzVM -ResourceGroupName CLD202 -Name Master-MySQL'
#         azurePowerShellVersion: 'LatestVersion'
  
#   - job: Start_Worker
#     displayName: Start Worker-IoT
#     pool:
#       vmImage: ubuntu-latest
#     steps:      
#     - task: AzurePowerShell@5
#       inputs:
#         azureSubscription: 'Azure subscription 1(1aab54f1-babe-4322-95b4-185df45b9d75)'
#         ScriptType: 'InlineScript'
#         Inline: 'Start-AzVM -ResourceGroupName CLD202 -Name Worker-IoT'
#         azurePowerShellVersion: 'LatestVersion'

- stage: Docker
  displayName: Deploy with Docker Swarm
  jobs:
  - job: Init_Swarm
    displayName: Initialize swarm
    steps:
    - bash: |
        OUTPUT=$(/usr/bin/docker info --format '{{.Swarm.LocalNodeState}}');
        echo $OUTPUT;

  - deployment: masterSwarm
    displayName: Swarm init on Master
    pool:
      vmImage: 'ubuntu-latest'
    environment: 
      name: Azure Swarm
      resourceType: VirtualMachine
      tags: master
    strategy:
      runOnce:
        deploy:   
            steps:
            - bash:
                if [ $( /usr/bin/docker info --format '{{.Swarm.LocalNodeState}}' ) != 'active' ]; then
                  /usr/bin/docker swarm init --advertise-addr 4.205.16.41;
                fi;
            - bash: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]$( /usr/bin/docker swarm join-token -q worker )"
              name: setvarStep
            - bash: echo $(setvarStep.myOutputVar)
              name: echovar

  - deployment: workerSwarm
    displayName: Swarm init on Worker
    dependsOn: masterSwarm
    variables:
      myVarFromDeploymentJob: $[ dependencies.masterSwarm.outputs['setvarStep.myOutputVar'] ]
    environment: 
      name: Azure Swarm
      resourceType: VirtualMachine
      tags: worker
    strategy:
      runOnce:
        deploy:   
            steps:
            - script: "echo $(myVarFromDeploymentJob)"
              name: echovar
            - bash:
                if [ $( /usr/bin/docker info --format '{{.Swarm.LocalNodeState}}' ) != 'active' ]; then
                /usr/bin/docker swarm join --token $(masterToken)  4.205.16.41:2377;
                fi;
                echo $(myVarFromJobA)
  # Set an output variable in a lifecycle hook of a deployment job executing canary strategy.
  - deployment: A
    pool:
      vmImage: 'ubuntu-latest'
    strategy:                  
      canary:      
        increments: [10,20]  # Creates multiple jobs, one for each increment. Output variable can be referenced with this.
        deploy:
          steps:
          - bash: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the deployment variable value"
            name: setvarStep
          - bash: echo $(setvarStep.myOutputVar)
            name: echovar

  # Map the variable from the job.
  - job: B
    dependsOn: A
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      myVarFromDeploymentJob: $[ dependencies.A.outputs['deploy_10.setvarStep.myOutputVar'] ]
    steps:
    - script: "echo $(myVarFromDeploymentJob)"
      name: echovar