# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker Hub'
          repository: '8cld202'
          command: 'build'
          Dockerfile: 'Web/Dockerfile'
          tags: 'web'
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker Hub'
          command: 'login'
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker Hub'
          repository: 'micmunger/8cld202'
          command: 'push'
          tags: 'web'
