version: '3.0'
services:
  web:
    container_name: 8CLD202-Serveur_Web
    ports:
      - "80:5000" # NECESSARY ports for Deployment
    build:
      context: ./Web
      dockerfile: Dockerfile
    volumes:
      - ./Web/app/:/app # Overrides Dockerfile COPY for development
    depends_on:
    - mysql_api
    - iot_api

  iot_api:
    container_name: 8CLD202-API_pour_IoTDB
    build:
      context: ./IoT_API
      dockerfile: Dockerfile
    ports:
      - "3456:5000" # NECESSARY ports for Deployment
    volumes:
      - ./IoT_API/app/:/app # Overrides Dockerfile COPY for development
    depends_on:
    - mysql_api

  mysql_api:
    container_name: 8CLD202-API_pour_MySQL
    build:
      context: ./MySQL_API
      dockerfile: Dockerfile
    volumes:
      - ./MySQL_API/app/:/app # Overrides Dockerfile COPY for development
    depends_on:
    - mysql_db

  mysql_db:
    container_name: 8CLD202-Base_de_Donnees_MySQL
    restart: always
    build:
      context: ./MySQL_DB
      dockerfile: Dockerfile

  iot_db:
    container_name: 8CLD202-Base_de_Donnees_IoTDB
    restart: always
    ports:
      - 6667:6667 # NECESSARY ports for Deployment
      - 9091:9091 # NECESSARY ports for Deployment
    build:
      context: ./IoT_DB
      dockerfile: Dockerfile