version: '1.0'

services:
  web:
    image: ${CI_REGISTRY_IMAGE}/web
    build:
      context: ./Web
      dockerfile: Web/Dockerfile

  db:
    image: ${CI_REGISTRY_IMAGE}/db
    build:
      context: ./DB
      dockerfile: DB/Dockerfile