version: '1.0'

services:
  web:
    image: micmunger/8cld202:web-latest
    ports:
      - "81:5000"
    build:
      context: ./Web
      dockerfile: Dockerfile

  db:
    image: micmunger/8cld202:db-latest
    ports:
      - "5000:5000"
    build:
      context: ./DB
      dockerfile: Dockerfile