# [INDEX]  (Obj_List)     Web - DB_API - DB_MySQL - List 
# [INDEX]  (Analytics)    Web - IoT_API - DB_IoT - Get Data + Process Data
# [CREATE] (Obj_Data)     Obj - IoT_API - DB_IoT - Add Data
# [CREATE] (Registration) Obj - IoT_API - DB_MySQL - Token 
# [CREATE] (Confirmation) Web - Approve - DB_API - Approve Token
# [UPDATE] (Name_Change)  Web - DB_API - DB_MySQL - Change Name
# [DELETE] (Deactivate)   Web - DB_API - DB_MySQL - Status Change
# [DELETE] (Obj_Data)     Obj - IoT_API - DB_IoT - Delete Data

version: '3.0'
services:
  web:
    container_name: 8CLD202-Serveur_Web
    ports:
      - "80:5000"
    build:
      context: ./Web
      dockerfile: Dockerfile
    volumes:
      - ./Web/app/:/app
    depends_on:
    - db_api

  db_api:
    container_name: 8CLD202-API_pour_MySQL
    ports:
      - "5011:5000"
    build:
      context: ./DB_API
      dockerfile: Dockerfile
    volumes:
      - ./DB_API/app/:/app
    depends_on:
    - bd_mysql

  bd_mysql:
    container_name: 8CLD202-Base_de_Donnees_MySQL
    restart: always
    build:
      context: ./DB_MySQL
      dockerfile: Dockerfile
    ports:
        - 3306:3306