version: '3.0'
services:
  web:
    container_name: 8CLD202-Serveur_Web
    ports:
      - "80:80"
    build:
      context: ./
      dockerfile: /k8s/web/Dockerfile
    depends_on:
    - mysql-api
    - iot-api

  iot-api:
    container_name: 8CLD202-API_pour_IoTDB
    build:
      context: ./
      dockerfile: /k8s/IoT_API/Dockerfile
    ports:
      - "3456:5000"
    depends_on:
    - mysql-api

  mysql-api:
    container_name: 8CLD202-API_pour_MySQL
    build:
      context: ./
      dockerfile: /k8s/MySQL_API/Dockerfile
    depends_on:
    - mysql-db

  mysql-db:
    container_name: 8CLD202-Base_de_Donnees_MySQL
    restart: always
    build:
      context: ./MySQL_DB
      dockerfile: Dockerfile

  iot-db:
    container_name: 8CLD202-Base_de_Donnees_IoTDB
    restart: always
    ports:
      - 6667:6667
      - 9091:9091
    build:
      context: ./IoT_DB
      dockerfile: Dockerfile