version: '3.0'
services:
  web:
    container_name: 8CLD202-Serveur_Web
    ports:
      - "80:5000"
    build:
      context: ./Web
      dockerfile: Dockerfile
    depends_on:
    - dbapi

  dbapi:
    container_name: 8CLD202-API_pour_BDD
    ports:
      - "5011:5000"
    build:
      context: ./DB_API
      dockerfile: Dockerfile
    volumes:
      - ./DB_API/app/:/app
    depends_on:
    - bdd

  bdd:
    container_name: 8CLD202-Base_de_Donnees
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: fakepassword
        MYSQL_DATABASE: IoTDatabase
        MYSQL_USER: IoTUser
        MYSQL_PASSWORD: IoTPassword
    ports:
        - 3306:3306
    volumes:
      - ./DB_API/sql/:/docker-entrypoint-initdb.d/